name: Test and build
on:
  push: #le pipeline se declenche sur chaque push sur main, donc apres merge.
    branches: [ main ]
  pull_request: #le pipeline se declenche sur chaque pull request vers main.
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install dependencies (if needed)
        run: sudo apt-get update && sudo apt-get install -y build-essential valgrind
      - name: Run tests
        run: |
          cc -v
          make clean
          make test && make test-valgrind
          if [ $? -ne 0 ]; then
            echo "Tests failed. Exiting with error."
            exit 1
          else
            echo "All tests passed successfully."
          fi

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install dependencies (if needed)
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build and Install
        run: |
          make clean
          make
          make install

  norminette:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install norminette if missing
        run: |
          if ! command -v norminette &> /dev/null; then
            python3 -m pip install --upgrade pip
            python3 -m pip install norminette
          fi

      - name: Run norminette on src
        run: |
          echo "Current dir: $(pwd)"
          ls -ls
          make norminette